version: "3.8"
name: lect_10_02_notes
services:
  pg:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  code :
    build: ./
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - pg

